import React from "react";
import "bootstrap/dist/css/bootstrap.min.css"; // Importing Bootstrap for styling

const Privacy = () => {
  return (
    <div className="container mt-5">
      <h1 className="text-center mb-4">Privacy Statement</h1>

      <p className="lead">
        This Privacy Policy is intended to inform you regarding the personal
        information that may be collected through SS Tech Services and how we
        use, share, and protect that information. By using this site, you agree
        to this Privacy Policy, and as such we strongly encourage our visitors
        to read through this content regularly to stay informed of its contents
        and any changes. In the following policy, “we, us, and site” are used to
        refer to SS Tech Services.
      </p>

      <h3><strong>Applicability of this Privacy Policy</strong></h3>
      <p>
        This Privacy Policy reflects the information that is collected and
        shared via sstechservices.com. For other distribution channels (email,
        social media, etc.), different rules may apply.
      </p>

      <h3><strong>Use of Information</strong></h3>
      <p>
        In efforts to better serve your needs, SS Tech Services collects and
        stores personal information that you choose to voluntarily provide
        through our contact forms and other means of communication in which you
        provide your information. The information collected may include but is
        not limited to your name, email address, phone number, and company name.
        The website may also auto-collect information to improve your user
        experience including your IP address, browser type, operating system,
        referring URLs, and actions taken on the site. This information may be
        used to offer you an improved user experience, to improve our site to
        better serve your needs, or to send periodic emails that may be relevant
        to your needs, respond to inquiries, questions, and/or other requests.
      </p>

      <p>
        We value your information and protect your privacy by utilizing this
        information only in a way that best benefits you. SS Tech Services does
        not rent, sell, or share personal information about you with other
        people or non-affiliated companies without your explicit approval outside
        of the following purposes:
      </p>
      <ul>
        <li>To provide products or services you’ve requested</li>
        <li>
          To provide the information to trusted entities who work on behalf of
          or with SS Tech Services under strict confidentiality agreements in
          order to help us communicate with you regarding relevant offers from
          SS Tech Services and our marketing partners. These companies do not
          have any independent right to further share or disseminate this
          information.
        </li>
        <li>
          To respond to subpoenas, court orders, or legal process, or to
          establish or exercise our legal rights or defend against legal claims
        </li>
        <li>
          To share the information in order to investigate, prevent, or take
          action against any illegal activities, suspected fraud, situations
          involving potential threats to the physical safety of any person, or
          as otherwise required by law
        </li>
        <li>
          To transfer information about you if SS Tech Services is acquired by
          or merged with another company
        </li>
      </ul>

      <h3><strong>Secured Information</strong></h3>
      <p>
        We adopt industry best standards for data collection, storage,
        processing practices, and security measures to protect you against
        unauthorized access, alteration, disclosure, or destruction of your
        personal information.
      </p>

      <h3><strong>Cookies</strong></h3>
      <p>
        Our site may use “cookies” to enhance and personalize your user
        experience. Cookies are generated by your web browser for record-keeping
        purposes and to track information regarding your website navigation.
        Permission of cookies can be modified through your own personal settings.
        You may choose to set your web browser to refuse cookies, or to alert you
        when cookies are being sent – however doing so may limit the
        functionalities of the site performance. Cookies are also used for
        security purposes, website statistical data, pages visited, files
        downloaded, and user path.
      </p>

      <h3><strong>Links to Other Websites</strong></h3>
      <p>
        In order to provide additional information or services, SS Tech Services
        may include links to external websites. Clicking on such a link will
        navigate you away from SS Tech Services’ site. Other site’s privacy
        practices may differ from our own. We do not endorse or make any
        representations regarding third-party websites. When clicking off the SS
        Tech Services site, we strongly encourage you to visit the other site’s
        Privacy Policy to ensure it meets the standards of your own personal
        preferences.
      </p>

      <h3><strong>Compliance with the Children’s Online Privacy Protection Act</strong></h3>
      <p>
        Protecting the privacy of children is important. The content of this site
        is not intended to attract or engage any individuals under the age of 13.
        For that reason, we never collect or maintain information at our site
        from those we know are under the age of 13.
      </p>

      <h3><strong>Your Information, Your Choices</strong></h3>
      <p>
        If you choose to no longer receive email notifications from SS Tech
        Services, you are free at any time to unsubscribe in order to cease from
        receiving these types of notifications. If you have provided us with your
        information, you may request to update, modify, or delete it as deemed
        necessary by contacting us.
      </p>

      <h3><strong>Changes to this Privacy Policy</strong></h3>
      <p>
        SS Tech Services retains the right to update this Privacy Policy at our
        discretion at any time. For the benefit of your open awareness and
        knowledge, we make every effort to notify users of policy changes. Prior
        versions of this policy are retained for records. We encourage our users
        to frequently check this page for any possible changes to stay informed on
        how we protect your personal information.
      </p>

      <h3><strong>Your Acceptance of These Terms</strong></h3>
      <p>
        By using this site, you signify your acceptance of this policy. If you do
        not agree to this policy, please do not use our site. Your continued use of
        the site now or following the posting of changes to this policy will be
        deemed as your acceptance to the site and any changes.
      </p>

      <h3><strong>Contacting Us</strong></h3>
      <p>
        If you have any questions regarding our Privacy Policy, the practices of
        this site, or your dealings with sstechservices.com, please contact us
        through our Contact Form, or with the following information:
      </p>
    </div>
  );
};

export default Privacy;
